package formularios;

import daos.CdDao;
import daos.MaterialDao;
import entidades.Cd;
import entidades.Material;
import entidades.Usuario;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CdForm extends javax.swing.JInternalFrame {

    private CdDao cdDao;
    private MaterialDao materialDao;
    private Usuario usuario;
    
    public CdForm(Usuario usuario) {
        initComponents();
        this.cdDao = new CdDao();
        this.materialDao = new MaterialDao();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUnidadesDisp = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtNumCanciones = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cd");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 27, 83, -1));

        jLabel2.setText("Titulo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 65, -1, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 62, 245, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 27, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 99, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 330, 95, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 330, 92, -1));

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensaje.setText(" ");
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 365, 347, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 27, -1, -1));

        jLabel4.setText("Artista:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 99, -1, -1));

        jLabel5.setText("Genero:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 139, -1, -1));

        jLabel6.setText("Duracion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 179, -1, -1));

        jLabel7.setText("Num Canciones:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 219, -1, -1));

        jLabel9.setText("Unidades Disp:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 259, -1, -1));
        getContentPane().add(txtUnidadesDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 256, 245, -1));
        getContentPane().add(txtArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 96, 245, -1));
        getContentPane().add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 136, 245, -1));
        getContentPane().add(txtNumCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 216, 245, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 176, 245, -1));

        jLabel10.setText("Ubicacion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 299, -1, -1));
        getContentPane().add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 296, 245, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        txtCodigo.setText("");
        txtTitulo.setText("");
        txtArtista.setText("");
        txtGenero.setText("");
        txtDuracion.setText("");
        txtNumCanciones.setText("");
        txtUnidadesDisp.setText("");
        txtUbicacion.setText("");
        lblMensaje.setText("");
    }
    
    private void llenarFormulario(Cd cd) {
        limpiar();
        if (cd == null) {
           lblMensaje.setText("Registro no encontrado");
        } else {
            txtCodigo.setText(cd.getCodigo());
            txtTitulo.setText(cd.getTitulo());
            txtArtista.setText(cd.getArtista());
            txtGenero.setText(cd.getGenero());
            txtDuracion.setText(cd.getDuracion());
            txtNumCanciones.setText(String.valueOf(cd.getNumCanciones()));
            txtUnidadesDisp.setText(String.valueOf(cd.getUnidadesDisp()));
            txtUbicacion.setText(cd.getUbicacion());
        }
    }
    
    private Cd obtenerDesdeFormulario() {
        Cd cd = new Cd();
        cd.setCodigo(txtCodigo.getText());
        cd.setTitulo(txtTitulo.getText());
        cd.setArtista(txtArtista.getText());
        cd.setGenero(txtGenero.getText());
        cd.setDuracion(txtDuracion.getText());
        cd.setNumCanciones(Integer.valueOf(txtNumCanciones.getText()));
        cd.setUnidadesDisp(Integer.valueOf(txtUnidadesDisp.getText()));
        cd.setUbicacion(txtUbicacion.getText());
        return cd;
    }
    
    private void registrarMaterial() {
        try {
            Material material = new Material();
            material.setCodigo(txtCodigo.getText());
            material.setIdUsuario(usuario.getIdUsuario());
            materialDao.registrarMaterial(material);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo = txtCodigo.getText();
        
        try {
            Cd cd = cdDao.obtenerCd(codigo);
            llenarFormulario(cd);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            Cd cd = obtenerDesdeFormulario();
            cdDao.registrarCd(cd);
            registrarMaterial();
            limpiar();
            lblMensaje.setText("Registrado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            Cd cd = obtenerDesdeFormulario();
            cdDao.modificarCd(cd);
            limpiar();
            lblMensaje.setText("Modificado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtCodigo.getText();
        
        try {
            cdDao.eliminarCd(codigo);
            limpiar();
            lblMensaje.setText("Eliminado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNumCanciones;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtUnidadesDisp;
    // End of variables declaration//GEN-END:variables
}
