package formularios;

import daos.CdDao;
import entidades.Cd;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class CdsForm extends javax.swing.JInternalFrame {

    public CdsForm() {
        initComponents();
        pintarTabla();
    }
    
    private Object[][] convertirAFilasDeTabla(List<Cd> cds) {
        Object[][] matriz = new Object[cds.size()][8];

        for (int i = 0; i < cds.size(); i++) {
            Cd cd = cds.get(i);
            matriz[i][0] = cd.getCodigo();
            matriz[i][1] = cd.getTitulo();
            matriz[i][2] = cd.getArtista();
            matriz[i][3] = cd.getGenero();
            matriz[i][4] = cd.getDuracion();
            matriz[i][5] = cd.getNumCanciones();
            matriz[i][6] = cd.getUnidadesDisp();
            matriz[i][7] = cd.getUbicacion();
        }

        return matriz;
    }
    
    private void pintarTabla() {
        CdDao cdDao = new CdDao();
        
        try {
            List<Cd> cds = cdDao.obtenerCds();
            Object[][] filasDeTabla = convertirAFilasDeTabla(cds);
            String[] titulosTabla = new String[] {"Codigo", "Titulo", "Artista", 
                "Genero", "Duracion", "Num Canciones", "Unidades Disp", "Ubicacion"};

            DefaultTableModel model = new DefaultTableModel(filasDeTabla, titulosTabla);
            tblCds.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCds = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cds");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Artista", "Genero", "Duracion", "Num Canciones", "Unidades Disp", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(tblCds);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 823, 120));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        pintarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCds;
    // End of variables declaration//GEN-END:variables
}
