package formularios;

import daos.DocumentoDao;
import entidades.Documento;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class DocumentosForm extends javax.swing.JInternalFrame {

    public DocumentosForm() {
        initComponents();
        pintarTabla();
    }
    
    private Object[][] convertirAFilasDeTabla(List<Documento> documentos) {
        Object[][] matriz = new Object[documentos.size()][7];

        for (int i = 0; i < documentos.size(); i++) {
            Documento documento = documentos.get(i);
            matriz[i][0] = documento.getCodigo();
            matriz[i][1] = documento.getTitulo();
            matriz[i][2] = documento.getAutor();
            matriz[i][3] = documento.getEditorial();
            matriz[i][4] = documento.getTematica();
            matriz[i][5] = documento.getUnidadesDisp();
            matriz[i][6] = documento.getUbicacion();
        }

        return matriz;
    }
    
    private void pintarTabla() {
        DocumentoDao documentoDao = new DocumentoDao();
        
        try {
            List<Documento> documentos = documentoDao.obtenerDocumentos();
            Object[][] filasDeTabla = convertirAFilasDeTabla(documentos);
            String[] titulosTabla = new String[] {"Codigo", "Titulo", "Autor", 
                "Editorial", "Tematica", "Unidades Disp", "Ubicacion"};

            DefaultTableModel model = new DefaultTableModel(filasDeTabla, titulosTabla);
            tblDocumentos.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocumentos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Documentos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Autor", "Editorial", "Tematica", "Unidades Disp", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(tblDocumentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 760, 120));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        pintarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDocumentos;
    // End of variables declaration//GEN-END:variables
}
