package formularios;

import daos.DvdDao;
import entidades.Dvd;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class DvdsForm extends javax.swing.JInternalFrame {

    public DvdsForm() {
        initComponents();
        pintarTabla();
    }
    
    private Object[][] convertirAFilasDeTabla(List<Dvd> dvds) {
        Object[][] matriz = new Object[dvds.size()][7];

        for (int i = 0; i < dvds.size(); i++) {
            Dvd dvd = dvds.get(i);
            matriz[i][0] = dvd.getCodigo();
            matriz[i][1] = dvd.getTitulo();
            matriz[i][2] = dvd.getDirector();
            matriz[i][3] = dvd.getDuracion();
            matriz[i][4] = dvd.getGenero();
            matriz[i][5] = dvd.getUnidadesDisp();
            matriz[i][6] = dvd.getUbicacion();
        }

        return matriz;
    }
    
    private void pintarTabla() {
        DvdDao dvdDao = new DvdDao();
        
        try {
            List<Dvd> dvds = dvdDao.obtenerDvds();
            Object[][] filasDeTabla = convertirAFilasDeTabla(dvds);
            String[] titulosTabla = new String[] {"Codigo", "Titulo", "Director", 
                "Duracion", "Genero", "Unidades Disp", "Ubicacion"};

            DefaultTableModel model = new DefaultTableModel(filasDeTabla, titulosTabla);
            tblDvds.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDvds = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dvds");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDvds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Director", "Duracion", "Genero", "Unidades Disp", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(tblDvds);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 814, 120));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        pintarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDvds;
    // End of variables declaration//GEN-END:variables
}
