package formularios;

import daos.ParametroSistemaDao;
import entidades.ParametroSistema;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ParametroSistemasForm extends javax.swing.JInternalFrame {

    private ParametroSistemaDao parametroSistemaDao;
    
    public ParametroSistemasForm() {
        initComponents();
        this.parametroSistemaDao = new ParametroSistemaDao();
        pintarTabla();
    }
    
    private Object[][] convertirAFilasDeTabla(List<ParametroSistema> parametroSistemas) {
        Object[][] matriz = new Object[parametroSistemas.size()][4];

        for (int i = 0; i < parametroSistemas.size(); i++) {
            ParametroSistema parametroSistema = parametroSistemas.get(i);
            matriz[i][0] = parametroSistema.getIdParametroSistema();
            matriz[i][1] = parametroSistema.getNombre();
            matriz[i][2] = parametroSistema.getDescripcion();
            matriz[i][3] = parametroSistema.getValor();
        }

        return matriz;
    }
    
    private void pintarTabla() {
        
        try {
            List<ParametroSistema> parametroSistemaes = parametroSistemaDao.obtenerParametroSistemas();
            Object[][] filasDeTabla = convertirAFilasDeTabla(parametroSistemaes);
            String[] titulosTabla = new String[] {"Id", "Nombre", "Descripcion" , "Valor"};

            DefaultTableModel model = new DefaultTableModel(filasDeTabla, titulosTabla);
            tblParametroSistemas.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblParametroSistemas = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Parametros de Sistema");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblParametroSistemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblParametroSistemas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 480, 120));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        pintarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblParametroSistemas;
    // End of variables declaration//GEN-END:variables
}
