package formularios;

import entidades.Rol;
import entidades.Usuario;
import javax.swing.JFrame;

public class PrincipalForm extends javax.swing.JFrame {

    private LoginForm loginForm;
    private Usuario usuario;
    
    private PrincipalForm() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
    
    public PrincipalForm(LoginForm loginForm, Usuario usuario, Rol rol) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.loginForm = loginForm;
        this.usuario = usuario;
        mostrarMenuPorRol(usuario, rol);
    }
    
    private void mostrarMenuPorRol(Usuario usuario, Rol rol) {
        jmAdministrador.setVisible(false);
        jmProfesor.setVisible(false);
        jmAlumno.setVisible(false);
        
        lblUsuarioYRol.setText("Usuario: " + usuario.getCarnet());
        
        if (rol.getNombre().equals("ADMINISTRADOR")) {
            jmAdministrador.setVisible(true);
        } else if (rol.getNombre().equals("PROFESOR")) {
            jmProfesor.setVisible(true);
        } else if (rol.getNombre().equals("ALUMNO")) {
            jmAlumno.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioYRol = new javax.swing.JLabel();
        jdpPrincipal = new javax.swing.JDesktopPane();
        menPrincipal = new javax.swing.JMenuBar();
        jmAdministrador = new javax.swing.JMenu();
        jmRoles = new javax.swing.JMenu();
        jmiListarRoles = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmiListarUsuarios = new javax.swing.JMenuItem();
        jmiRegModEliUsuarios = new javax.swing.JMenuItem();
        jmParametrosSistema = new javax.swing.JMenu();
        jmiListarParamSist = new javax.swing.JMenuItem();
        jmiAgrModEliParamSist = new javax.swing.JMenuItem();
        jmMateriales = new javax.swing.JMenu();
        jmLibros = new javax.swing.JMenu();
        jmiListarLibros = new javax.swing.JMenuItem();
        jmiRegModEliLibros = new javax.swing.JMenuItem();
        jmRevistas = new javax.swing.JMenu();
        jmiListarRevistas = new javax.swing.JMenuItem();
        jmiRegModEliRevistas = new javax.swing.JMenuItem();
        jmCds = new javax.swing.JMenu();
        jmiListarCds = new javax.swing.JMenuItem();
        jmiRegModEliCds = new javax.swing.JMenuItem();
        jmDvds = new javax.swing.JMenu();
        jmiListarDvds = new javax.swing.JMenuItem();
        jmiRegModEliDvds = new javax.swing.JMenuItem();
        jmObras = new javax.swing.JMenu();
        jmiListarObras = new javax.swing.JMenuItem();
        jmiRegModEliObras = new javax.swing.JMenuItem();
        jmTesis = new javax.swing.JMenu();
        jmiListarTesis = new javax.swing.JMenuItem();
        jmiRegModEliTesis = new javax.swing.JMenuItem();
        jmDocumentos = new javax.swing.JMenu();
        jmiListarDocumentos = new javax.swing.JMenuItem();
        jmiRegModEliDocumentos = new javax.swing.JMenuItem();
        jmPrestamos = new javax.swing.JMenu();
        jmiListarPrestamosAdm = new javax.swing.JMenuItem();
        jmiPrestarDevolver = new javax.swing.JMenuItem();
        jmProfesor = new javax.swing.JMenu();
        jmPrestamosPro = new javax.swing.JMenu();
        jmiListarPrestamosPro = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmPrestamosAlu = new javax.swing.JMenu();
        jmiListarPrestamosAlu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Colegio Don Bosco");
        setSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblUsuarioYRol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuarioYRol.setForeground(new java.awt.Color(0, 0, 153));
        lblUsuarioYRol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioYRol.setText(" ");
        lblUsuarioYRol.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jdpPrincipal.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jmAdministrador.setText("Administrador");

        jmRoles.setText("Roles");

        jmiListarRoles.setText("Listar");
        jmiListarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarRolesActionPerformed(evt);
            }
        });
        jmRoles.add(jmiListarRoles);

        jmAdministrador.add(jmRoles);

        jmUsuarios.setText("Usuarios");

        jmiListarUsuarios.setText("Listar");
        jmiListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiListarUsuarios);

        jmiRegModEliUsuarios.setText("Registrar/Modificar/Eliminar");
        jmiRegModEliUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiRegModEliUsuarios);

        jmAdministrador.add(jmUsuarios);

        jmParametrosSistema.setText("Parametros de Sistema");

        jmiListarParamSist.setText("Listar");
        jmiListarParamSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarParamSistActionPerformed(evt);
            }
        });
        jmParametrosSistema.add(jmiListarParamSist);

        jmiAgrModEliParamSist.setText("Agregar/Modificar/Eliminar");
        jmiAgrModEliParamSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgrModEliParamSistActionPerformed(evt);
            }
        });
        jmParametrosSistema.add(jmiAgrModEliParamSist);

        jmAdministrador.add(jmParametrosSistema);

        jmMateriales.setText("Materiales");

        jmLibros.setText("Libros");

        jmiListarLibros.setText("Listar");
        jmiListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarLibrosActionPerformed(evt);
            }
        });
        jmLibros.add(jmiListarLibros);

        jmiRegModEliLibros.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliLibrosActionPerformed(evt);
            }
        });
        jmLibros.add(jmiRegModEliLibros);

        jmMateriales.add(jmLibros);

        jmRevistas.setText("Revistas");

        jmiListarRevistas.setText("Listar");
        jmiListarRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarRevistasActionPerformed(evt);
            }
        });
        jmRevistas.add(jmiListarRevistas);

        jmiRegModEliRevistas.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliRevistasActionPerformed(evt);
            }
        });
        jmRevistas.add(jmiRegModEliRevistas);

        jmMateriales.add(jmRevistas);

        jmCds.setText("Cds");

        jmiListarCds.setText("Listar");
        jmiListarCds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarCdsActionPerformed(evt);
            }
        });
        jmCds.add(jmiListarCds);

        jmiRegModEliCds.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliCds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliCdsActionPerformed(evt);
            }
        });
        jmCds.add(jmiRegModEliCds);

        jmMateriales.add(jmCds);

        jmDvds.setText("Dvds");

        jmiListarDvds.setText("Listar");
        jmiListarDvds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarDvdsActionPerformed(evt);
            }
        });
        jmDvds.add(jmiListarDvds);

        jmiRegModEliDvds.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliDvds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliDvdsActionPerformed(evt);
            }
        });
        jmDvds.add(jmiRegModEliDvds);

        jmMateriales.add(jmDvds);

        jmObras.setText("Obras");

        jmiListarObras.setText("Listar");
        jmiListarObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarObrasActionPerformed(evt);
            }
        });
        jmObras.add(jmiListarObras);

        jmiRegModEliObras.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliObrasActionPerformed(evt);
            }
        });
        jmObras.add(jmiRegModEliObras);

        jmMateriales.add(jmObras);

        jmTesis.setText("Tesis");

        jmiListarTesis.setText("Listar");
        jmiListarTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarTesisActionPerformed(evt);
            }
        });
        jmTesis.add(jmiListarTesis);

        jmiRegModEliTesis.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliTesisActionPerformed(evt);
            }
        });
        jmTesis.add(jmiRegModEliTesis);

        jmMateriales.add(jmTesis);

        jmDocumentos.setText("Documentos");

        jmiListarDocumentos.setText("Listar");
        jmiListarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarDocumentosActionPerformed(evt);
            }
        });
        jmDocumentos.add(jmiListarDocumentos);

        jmiRegModEliDocumentos.setText("Registrar/Modifiar/Eliminar");
        jmiRegModEliDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliDocumentosActionPerformed(evt);
            }
        });
        jmDocumentos.add(jmiRegModEliDocumentos);

        jmMateriales.add(jmDocumentos);

        jmAdministrador.add(jmMateriales);

        jmPrestamos.setText("Prestamos");

        jmiListarPrestamosAdm.setText("Listar");
        jmiListarPrestamosAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarPrestamosAdmActionPerformed(evt);
            }
        });
        jmPrestamos.add(jmiListarPrestamosAdm);

        jmiPrestarDevolver.setText("Prestar/Devolver");
        jmiPrestarDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrestarDevolverActionPerformed(evt);
            }
        });
        jmPrestamos.add(jmiPrestarDevolver);

        jmAdministrador.add(jmPrestamos);

        menPrincipal.add(jmAdministrador);

        jmProfesor.setText("Profesor");

        jmPrestamosPro.setText("Prestamos");

        jmiListarPrestamosPro.setText("Listar");
        jmiListarPrestamosPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarPrestamosProActionPerformed(evt);
            }
        });
        jmPrestamosPro.add(jmiListarPrestamosPro);

        jmProfesor.add(jmPrestamosPro);

        menPrincipal.add(jmProfesor);

        jmAlumno.setText("Alumno");

        jmPrestamosAlu.setText("Prestamos");

        jmiListarPrestamosAlu.setText("Listar");
        jmiListarPrestamosAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarPrestamosAluActionPerformed(evt);
            }
        });
        jmPrestamosAlu.add(jmiListarPrestamosAlu);

        jmAlumno.add(jmPrestamosAlu);

        menPrincipal.add(jmAlumno);

        setJMenuBar(menPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 698, Short.MAX_VALUE)
                        .addComponent(lblUsuarioYRol, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdpPrincipal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblUsuarioYRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.loginForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.loginForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jmiListarPrestamosAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarPrestamosAluActionPerformed
        PrestamosProAluForm prestamosForm = new PrestamosProAluForm(usuario);
        prestamosForm.setSize(900, 250);
        jdpPrincipal.add(prestamosForm);
        prestamosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarPrestamosAluActionPerformed

    private void jmiRegModEliUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliUsuariosActionPerformed
        UsuarioForm usuarioForm = new UsuarioForm();
        usuarioForm.setSize(461, 372);
        jdpPrincipal.add(usuarioForm);
        usuarioForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliUsuariosActionPerformed

    private void jmiListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarUsuariosActionPerformed
        UsuariosForm usuariosForm = new UsuariosForm();
        usuariosForm.setSize(900, 250);
        jdpPrincipal.add(usuariosForm);
        usuariosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarUsuariosActionPerformed

    private void jmiListarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarRolesActionPerformed
        RolesForm rolesForm = new RolesForm();
        rolesForm.setSize(550, 250);
        jdpPrincipal.add(rolesForm);
        rolesForm.setVisible(true);
    }//GEN-LAST:event_jmiListarRolesActionPerformed

    private void jmiListarPrestamosProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarPrestamosProActionPerformed
        PrestamosProAluForm prestamosProAluForm = new PrestamosProAluForm(usuario);
        prestamosProAluForm.setSize(900, 250);
        jdpPrincipal.add(prestamosProAluForm);
        prestamosProAluForm.setVisible(true);
    }//GEN-LAST:event_jmiListarPrestamosProActionPerformed

    private void jmiListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarLibrosActionPerformed
        LibrosForm librosForm = new LibrosForm();
        librosForm.setSize(900, 250);
        jdpPrincipal.add(librosForm);
        librosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarLibrosActionPerformed

    private void jmiRegModEliLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliLibrosActionPerformed
        LibroForm libroForm = new LibroForm(usuario);
        libroForm.setSize(460, 485);
        jdpPrincipal.add(libroForm);
        libroForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliLibrosActionPerformed

    private void jmiListarRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarRevistasActionPerformed
        RevistasForm revistasForm = new RevistasForm();
        revistasForm.setSize(900, 250);
        jdpPrincipal.add(revistasForm);
        revistasForm.setVisible(true);
    }//GEN-LAST:event_jmiListarRevistasActionPerformed

    private void jmiRegModEliRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliRevistasActionPerformed
        RevistaForm revistaForm = new RevistaForm(usuario);
        revistaForm.setSize(460, 402);
        jdpPrincipal.add(revistaForm);
        revistaForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliRevistasActionPerformed

    private void jmiListarCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarCdsActionPerformed
        CdsForm cdsForm = new CdsForm();
        cdsForm.setSize(900, 250);
        jdpPrincipal.add(cdsForm);
        cdsForm.setVisible(true);
    }//GEN-LAST:event_jmiListarCdsActionPerformed

    private void jmiRegModEliCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliCdsActionPerformed
        CdForm cdForm = new CdForm(usuario);
        cdForm.setSize(464, 432);
        jdpPrincipal.add(cdForm);
        cdForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliCdsActionPerformed

    private void jmiListarDvdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarDvdsActionPerformed
        DvdsForm dvdsForm = new DvdsForm();
        dvdsForm.setSize(900, 250);
        jdpPrincipal.add(dvdsForm);
        dvdsForm.setVisible(true);
    }//GEN-LAST:event_jmiListarDvdsActionPerformed

    private void jmiRegModEliDvdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliDvdsActionPerformed
        DvdForm dvdForm = new DvdForm(usuario);
        dvdForm.setSize(464, 432);
        jdpPrincipal.add(dvdForm);
        dvdForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliDvdsActionPerformed

    private void jmiListarObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarObrasActionPerformed
        ObrasForm obrasForm = new ObrasForm();
        obrasForm.setSize(900, 250);
        jdpPrincipal.add(obrasForm);
        obrasForm.setVisible(true);
    }//GEN-LAST:event_jmiListarObrasActionPerformed

    private void jmiRegModEliObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliObrasActionPerformed
        ObraForm obraForm = new ObraForm(usuario);
        obraForm.setSize(464, 432);
        jdpPrincipal.add(obraForm);
        obraForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliObrasActionPerformed

    private void jmiListarTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarTesisActionPerformed
        TesisesForm tesisesForm = new TesisesForm();
        tesisesForm.setSize(900, 250);
        jdpPrincipal.add(tesisesForm);
        tesisesForm.setVisible(true);
    }//GEN-LAST:event_jmiListarTesisActionPerformed

    private void jmiRegModEliTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliTesisActionPerformed
        TesisForm tesisForm = new TesisForm(usuario);
        tesisForm.setSize(464, 432);
        jdpPrincipal.add(tesisForm);
        tesisForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliTesisActionPerformed

    private void jmiListarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarDocumentosActionPerformed
        DocumentosForm documentosForm = new DocumentosForm();
        documentosForm.setSize(900, 250);
        jdpPrincipal.add(documentosForm);
        documentosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarDocumentosActionPerformed

    private void jmiRegModEliDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliDocumentosActionPerformed
        DocumentoForm documentoForm = new DocumentoForm(usuario);
        documentoForm.setSize(464, 432);
        jdpPrincipal.add(documentoForm);
        documentoForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliDocumentosActionPerformed

    private void jmiListarParamSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarParamSistActionPerformed
        ParametroSistemasForm parametroSistemasForm = new ParametroSistemasForm();
        parametroSistemasForm.setSize(550, 250);
        jdpPrincipal.add(parametroSistemasForm);
        parametroSistemasForm.setVisible(true);
    }//GEN-LAST:event_jmiListarParamSistActionPerformed

    private void jmiAgrModEliParamSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgrModEliParamSistActionPerformed
        ParametroSistemaForm parametroSistemaForm = new ParametroSistemaForm(usuario);
        parametroSistemaForm.setSize(464, 332);
        jdpPrincipal.add(parametroSistemaForm);
        parametroSistemaForm.setVisible(true);
    }//GEN-LAST:event_jmiAgrModEliParamSistActionPerformed

    private void jmiPrestarDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrestarDevolverActionPerformed
        PrestamoForm prestamoForm = new PrestamoForm();
        prestamoForm.setSize(510, 370);
        jdpPrincipal.add(prestamoForm);
        prestamoForm.setVisible(true);
    }//GEN-LAST:event_jmiPrestarDevolverActionPerformed

    private void jmiListarPrestamosAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarPrestamosAdmActionPerformed
        PrestamosAdmForm prestamosAdmForm = new PrestamosAdmForm(usuario);
        prestamosAdmForm.setSize(900, 250);
        jdpPrincipal.add(prestamosAdmForm);
        prestamosAdmForm.setVisible(true);
    }//GEN-LAST:event_jmiListarPrestamosAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmAdministrador;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmCds;
    private javax.swing.JMenu jmDocumentos;
    private javax.swing.JMenu jmDvds;
    private javax.swing.JMenu jmLibros;
    private javax.swing.JMenu jmMateriales;
    private javax.swing.JMenu jmObras;
    private javax.swing.JMenu jmParametrosSistema;
    private javax.swing.JMenu jmPrestamos;
    private javax.swing.JMenu jmPrestamosAlu;
    private javax.swing.JMenu jmPrestamosPro;
    private javax.swing.JMenu jmProfesor;
    private javax.swing.JMenu jmRevistas;
    private javax.swing.JMenu jmRoles;
    private javax.swing.JMenu jmTesis;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuItem jmiAgrModEliParamSist;
    private javax.swing.JMenuItem jmiListarCds;
    private javax.swing.JMenuItem jmiListarDocumentos;
    private javax.swing.JMenuItem jmiListarDvds;
    private javax.swing.JMenuItem jmiListarLibros;
    private javax.swing.JMenuItem jmiListarObras;
    private javax.swing.JMenuItem jmiListarParamSist;
    private javax.swing.JMenuItem jmiListarPrestamosAdm;
    private javax.swing.JMenuItem jmiListarPrestamosAlu;
    private javax.swing.JMenuItem jmiListarPrestamosPro;
    private javax.swing.JMenuItem jmiListarRevistas;
    private javax.swing.JMenuItem jmiListarRoles;
    private javax.swing.JMenuItem jmiListarTesis;
    private javax.swing.JMenuItem jmiListarUsuarios;
    private javax.swing.JMenuItem jmiPrestarDevolver;
    private javax.swing.JMenuItem jmiRegModEliCds;
    private javax.swing.JMenuItem jmiRegModEliDocumentos;
    private javax.swing.JMenuItem jmiRegModEliDvds;
    private javax.swing.JMenuItem jmiRegModEliLibros;
    private javax.swing.JMenuItem jmiRegModEliObras;
    private javax.swing.JMenuItem jmiRegModEliRevistas;
    private javax.swing.JMenuItem jmiRegModEliTesis;
    private javax.swing.JMenuItem jmiRegModEliUsuarios;
    private javax.swing.JLabel lblUsuarioYRol;
    private javax.swing.JMenuBar menPrincipal;
    // End of variables declaration//GEN-END:variables
}
