package formularios;

import daos.TesisDao;
import entidades.Tesis;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class TesisesForm extends javax.swing.JInternalFrame {

    public TesisesForm() {
        initComponents();
        pintarTabla();
    }
    
    private Object[][] convertirAFilasDeTabla(List<Tesis> tesiss) {
        Object[][] matriz = new Object[tesiss.size()][8];

        for (int i = 0; i < tesiss.size(); i++) {
            Tesis tesis = tesiss.get(i);
            matriz[i][0] = tesis.getCodigo();
            matriz[i][1] = tesis.getTitulo();
            matriz[i][2] = tesis.getAutor();
            matriz[i][3] = tesis.getEditorial();
            matriz[i][4] = tesis.getFacultad();
            matriz[i][5] = tesis.getCarrera();
            matriz[i][6] = tesis.getUnidadesDisp();
            matriz[i][7] = tesis.getUbicacion();
        }

        return matriz;
    }
    
    private void pintarTabla() {
        TesisDao tesisDao = new TesisDao();
        
        try {
            List<Tesis> tesiss = tesisDao.obtenerTesises();
            Object[][] filasDeTabla = convertirAFilasDeTabla(tesiss);
            String[] titulosTabla = new String[] {"Codigo", "Titulo", "Autor", 
                "Editorial", "Facultad", "Carrera", "Unidades Disp", "Ubicacion"};

            DefaultTableModel model = new DefaultTableModel(filasDeTabla, titulosTabla);
            tblTesises.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTesises = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tesis");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTesises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Autor", "Num Pagina", "Editorial", "ISBN", "Anio Pub", "Unidades Disp", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(tblTesises);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 760, 120));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        pintarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTesises;
    // End of variables declaration//GEN-END:variables
}
