package formularios;

import daos.RolDao;
import daos.UsuarioDao;
import entidades.Rol;
import entidades.Usuario;
import java.util.List;

public class UsuarioForm extends javax.swing.JInternalFrame {

    private UsuarioDao usuarioDao;
    private RolDao rolDao;
    
    public UsuarioForm() {
        initComponents();
        this.usuarioDao = new UsuarioDao();
        this.rolDao = new RolDao();
        cargarListaRoles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        getContentPane().add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 27, 83, -1));

        jLabel2.setText("Carnet:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 127, -1, -1));
        getContentPane().add(txtCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 124, 245, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 27, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, 99, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 241, 95, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 241, 92, -1));

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensaje.setText(" ");
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 276, 347, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 27, -1, -1));

        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 161, -1, -1));

        jLabel7.setText("Rol:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 201, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 158, 245, -1));

        getContentPane().add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 198, 245, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Autogenerado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 56, -1, -1));

        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 87, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 84, 245, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarListaRoles() {
        try {
            // Obtenemos la lista de roles de la BD
            List<Rol> roles = rolDao.obtenerRoles();
            // Limpiamos el combobox actual (por si tuviera algo)
            cmbRol.removeAllItems();
            // Iteramos la lista de roles
            for (Rol rol : roles) {
                // Por cada rol de la lista, agregamos su nombre y id al combobox
                // restamos 1 porque los items empiezan desde CERO
                cmbRol.insertItemAt(rol.getNombre(), rol.getIdRol() - 1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void limpiar() {
        txtIdUsuario.setText("");
        txtNombre.setText("");
        txtCarnet.setText("");
        txtPassword.setText("");
        cmbRol.setSelectedIndex(-1); // -1 significa no seleccionar nada
        lblMensaje.setText("");
    }
    
    private void llenarFormulario(Usuario usuario) {
        limpiar();
        if (usuario == null) {
           lblMensaje.setText("Registro no encontrado");
        } else {
            txtIdUsuario.setText(String.valueOf(usuario.getIdUsuario()));
            txtNombre.setText(usuario.getNombre());
            txtCarnet.setText(usuario.getCarnet());
            txtPassword.setText(usuario.getPassword());
            // restamos 1 porque los items empiezan desde CERO
            cmbRol.setSelectedIndex(usuario.getIdRol() - 1); 
        }
    }
    
    private Usuario obtenerDesdeFormulario() {
        Usuario usuario = new Usuario();
        if(txtIdUsuario.getText() != null && !txtIdUsuario.getText().isEmpty()) {
            usuario.setIdUsuario(Integer.valueOf(txtIdUsuario.getText()));
        }
        usuario.setNombre(txtNombre.getText());
        usuario.setCarnet(txtCarnet.getText());
        usuario.setPassword(txtPassword.getText());
        usuario.setIdRol(cmbRol.getSelectedIndex() + 1);
        return usuario;
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Integer id = Integer.valueOf(txtIdUsuario.getText());
        
        try {
            Usuario usuario = usuarioDao.obtenerUsuario(id);
            llenarFormulario(usuario);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            Usuario usuario = obtenerDesdeFormulario();
            usuarioDao.registrarUsuario(usuario);
            limpiar();
            lblMensaje.setText("Registrado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            Usuario usuario = obtenerDesdeFormulario();
            usuarioDao.modificarUsuario(usuario);
            limpiar();
            lblMensaje.setText("Modificado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Integer id = Integer.valueOf(txtIdUsuario.getText());
        
        try {
            usuarioDao.eliminarUsuario(id);
            limpiar();
            lblMensaje.setText("Eliminado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
